### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by CWYuan08** [CCIVR/ccivr2#2]
Hi @CCIVR , thank you very much sharing the tool, we would like to try CCIVR2. but after pip install. I cannot run it and the issue is:

lib/python3.7/site-packages/ccivr2/ccivr2.py", line 61
    "TES comparison":"(min1 >= max0 + {min}) & (min1 <= max0 + {max})".format(max=tes_range[0], max=tes_range[1])

Could you please help me on this?

Many thanks!
CW

**Comment by CCIVR** [comment]
Hello, CW. So, you could install CCIVR2, but it did not run, right? Which file did you try? Is that a test file of ours?

**Comment by CWYuan08** [comment]
Dear @CCIVR,

although installation was completed, but when I run ccivr2 (by just typing ccivr2) I got this error:

Traceback (most recent call last):
  File "/mnt/home3/miniconda3/envs/bulk_RNA_seq/bin/ccivr2", line 5, in <module>
    from ccivr2.ccivr2 import main
  File "/mnt/home3/miniconda3/envs/bulk_RNA_seq/lib/python3.7/site-packages/ccivr2/ccivr2.py", line 61
    "TES comparison":"(min1 >= max0 + {min}) & (min1 <= max0 + {max})".format(max=tes_range[0], max=tes_range[1])
                                                                                               ^
SyntaxError: keyword argument repeated

I tried to reinstall, got the same error. 

Thank you for your help!

Best,
CW

**Comment by CCIVR** [comment]
Dear @CWYuan08,

Thank you for reporting an issue with our software. 
We apologize for some bugs in CCIVR2.
We have now fixed them and confirmed that it runs successfully at least in our hand.
So, please install ccivr2 again as you previously did, and try the running of the ccivr2 again with the test file or your own.

you can find and download the test_file at 
CCIVR/ccivr2/data/ESCs_differentiation_exp_genes.csv

If there's still something wrong, please let me know.
I hope it helps you!

Best,
CCIVR team

**Comment by CWYuan08** [comment]
@CCIVR, thank you very much for your help!
I have managed to install in and tried to run with my csv file, however, it says No genes extracted when I Select identification mode [1/2/3]: 1, I have attached top 200 rows of my input file (62646 rows in the original file, this is human data). I used the reference file as listed on your github. 
[cancer_exp_genes_partial.csv](https://github.com/CCIVR/ccivr2/files/15223920/cancer_exp_genes_partial.csv)

Many thanks again!
Best,
CW

**Comment by CCIVR** [comment]
Hello CW,

One question. Does our test_file, "ESCs_differentiation_exp_genes.csv" work in your hand?
I found a difference between our test_file and your input_file that the strand column should be "+" or "-" but your file is "-1" or "1".
That's why the result said, "No genes extracted", I imagine.
Could you change the strand column as from "1" to "+" and from "-1" to "-"?

Best,
CCIVR team

**Comment by CCIVR** [comment]
Hello again,

So, CW, could you manage to run CCIVR?
It would be great if you could let me know the situation.
Maybe we can help you, again.

Best,
CCIVR team
